#application.yml
spring:
  config:
    import: classpath:application-db.yml
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    open-in-view: false

  security:
    user:
      name: admin             # 기본 사용자 이름 설정
      password: adminpassword  # 기본 비밀번호 설정 (운영 환경에서는 암호화된 비밀번호 사용하는 것이 좋음)

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: DEBUG   # Spring Security 로그 레벨 추가
    com.min.i.memory_BE: DEBUG


---
spring.config.activate.on-profile: local
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

---
spring.config.activate.on-profile: dev
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.dev.ip}/${database.dev.name}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${database.dev.username}
    password: ${database.dev.password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true

---

spring:
  mail:
    host: smtp.naver.com
    port: 465
    username:  ${NAVER_MAIL_USERNAME} # 네이버 이메일 주소
    password:  ${NAVER_MAIL_PASSWORD} # 이메일 비밀번호
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
---
spring:
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${GMAIL_MAIL_USERNAME} # Gmail 이메일 주소
    password: ${GMAIL_MAIL_PASSWORD} # Gmail 앱 비밀번호
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true



