spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/memory?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      data-locations: classpath:data-dev.sql
      continue-on-error: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.min.i.memory_BE: debug

jwt:
  secret: ${JWT_SECRET:your-default-secret-key-here}
  access-token-validity: 3600
  refresh-token-validity: 86400

aws:
  s3:
    bucket: memory-bucket
    region: ap-northeast-2
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: true
      file-size-threshold: 0

  config:
    import:
      - classpath:application-db.yml
      - classpath:application-key.yml

  # 기본 데이터베이스 설정 추가
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/memorydb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  
  # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    open-in-view: false

  security:
    user:
      name: admin
      password: adminpassword

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${GMAIL_MAIL_USERNAME}
    password: ${GMAIL_MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true

# 프론트엔드 URL 설정
frontend:
  url: http://localhost:3000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: DEBUG
    com.min.i.memory_BE: DEBUG
    com.min.i.memory_BE.global.service.S3Service: DEBUG
    com.min.i.memory_BE.domain.user.service.UserService: DEBUG
    com.amazonaws: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
  show-actuator: true

naver:
  oauth:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: http://localhost:8080/oauth/callback?provider=naver
    token-url: https://nid.naver.com/oauth2.0/token
    auth-url: https://nid.naver.com/oauth2.0/authorize

kakao:
  oauth:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    token-url: https://kauth.kakao.com/oauth/token
    auth-url: https://kauth.kakao.com/oauth/authorize
    redirect-uri: http://localhost:8080/oauth/callback?provider=kakao

google:
  oauth:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    auth-url: https://accounts.google.com/o/oauth2/v2/auth
    token-url: https://oauth2.googleapis.com/token
    redirect-uri: http://localhost:8080/oauth/callback?provider=google

# FastAPI 서버 설정
fastapi:
  server:
    url: http://localhost:8000  # FastAPI 서버 주소
  connection:
    timeout: 5000  # 연결 타임아웃 (ms)
  read:
    timeout: 30000  # 읽기 타임아웃 (ms)

---
spring.config.activate.on-profile: local
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/memorydb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  sql:
    init:
      mode: always
      platform: h2

---
spring.config.activate.on-profile: dev
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${database.dev.ip}/${database.dev.name}?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${database.dev.username}
    password: ${database.dev.password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

# Google Cloud Speech 설정
google:
  speech:
    language: ko-KR
    credentials-file: classpath:keys/google-credentials.json

spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data-dev.sql
      continue-on-error: true

